export type DemoAthlete  = { name: string; event: string };
export type DemoDonation = { donor_name: string; amount_cents: number; athlete_name: string; message: string };
export type DemoSponsor  = { name: string; url: string; tier: "gold" | "silver" | "bronze" };
export type DemoFundUse  = { icon: string; title: string; description: string; sort_order: number };

export type DemoTemplate = {
  id:              string;
  sport:           string;
  icon:            string;
  school_name:     string;
  mascot:          string;
  season:          string;
  location:        string;
  primary_color:   string;
  secondary_color: string;
  goal_cents:      number;
  default_slug:    string;
  description:     string;
  coach_name:      string;
  layout_variant:  "classic" | "premium";
  athletes:        DemoAthlete[];
  donations:       DemoDonation[];
  sponsors:        DemoSponsor[];
  fund_uses:       DemoFundUse[];
};

export const DEMO_TEMPLATES: DemoTemplate[] = [
  {
    id:              "football",
    sport:           "Football",
    icon:            "🏈",
    school_name:     "Riverside High School",
    mascot:          "Eagles",
    season:          "Fall 2026",
    location:        "Riverside, CA",
    primary_color:   "#1a1a2e",
    secondary_color: "#e94560",
    goal_cents:      1500000,
    default_slug:    "demo-riverside-football",
    description:     "Full varsity football program — 10 athletes, game-day sponsors, and realistic donor history.",
    coach_name:      "Coach Alex Reynolds",
    layout_variant:  "classic",
    athletes: [
      { name: "Marcus Thompson",  event: "Quarterback" },
      { name: "Jaylen Brooks",    event: "Running Back" },
      { name: "Tyler Santos",     event: "Wide Receiver" },
      { name: "Devon Clark",      event: "Offensive Line" },
      { name: "Malik Williams",   event: "Defensive End" },
      { name: "Chase Rivera",     event: "Linebacker" },
      { name: "Jordan Mitchell",  event: "Cornerback" },
      { name: "Dylan Foster",     event: "Safety" },
      { name: "Caleb Hughes",     event: "Kicker" },
      { name: "Noah Garcia",      event: "Tight End" },
    ],
    donations: [
      { donor_name: "James A.",   amount_cents:  25000, athlete_name: "Marcus Thompson", message: "Go Eagles!" },
      { donor_name: "Sarah M.",   amount_cents:  10000, athlete_name: "Jaylen Brooks",   message: "" },
      { donor_name: "Robert K.",  amount_cents: 100000, athlete_name: "Tyler Santos",    message: "Great season so far!" },
      { donor_name: "Linda P.",   amount_cents:   7500, athlete_name: "Devon Clark",     message: "" },
      { donor_name: "Michael T.", amount_cents:  15000, athlete_name: "Malik Williams",  message: "" },
      { donor_name: "Jessica R.", amount_cents:  25000, athlete_name: "Chase Rivera",    message: "Proud supporter!" },
      { donor_name: "David L.",   amount_cents: 200000, athlete_name: "Marcus Thompson", message: "Proud of this team!" },
      { donor_name: "Amanda W.",  amount_cents:  50000, athlete_name: "Jordan Mitchell", message: "" },
    ],
    sponsors: [
      { name: "Valley Automotive Group",    url: "https://example.com", tier: "gold"   },
      { name: "Sunrise Insurance Partners", url: "https://example.com", tier: "silver" },
      { name: "Riverside Coffee Co.",       url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "✈️", title: "Travel & Transportation",  description: "Away game buses and championship travel",        sort_order: 0 },
      { icon: "📋", title: "Game Film Software",       description: "Video analysis tools for coaching staff",        sort_order: 1 },
      { icon: "👕", title: "Team Uniforms",            description: "New home and away game uniforms for all players", sort_order: 2 },
      { icon: "💪", title: "Weight Room Equipment",    description: "Upgraded strength and conditioning equipment",    sort_order: 3 },
      { icon: "🍱", title: "Pre-Game Meals",           description: "Team nutrition program on game days",             sort_order: 4 },
    ],
  },
  {
    id:              "basketball",
    sport:           "Basketball",
    icon:            "🏀",
    school_name:     "Westwood Academy",
    mascot:          "Lions",
    season:          "Winter 2026",
    location:        "Westwood, CA",
    primary_color:   "#003566",
    secondary_color: "#ffd60a",
    goal_cents:       800000,
    default_slug:    "demo-westwood-basketball",
    description:     "Boys varsity basketball — 9 players, booster club sponsors, and multi-game donor activity.",
    coach_name:      "Coach Dana Harris",
    layout_variant:  "classic",
    athletes: [
      { name: "Isaiah Cooper",    event: "Point Guard" },
      { name: "Darius Webb",      event: "Shooting Guard" },
      { name: "Trevon Miles",     event: "Small Forward" },
      { name: "Kendall Price",    event: "Power Forward" },
      { name: "Antoine Jackson",  event: "Center" },
      { name: "Elijah Ross",      event: "Guard" },
      { name: "Marcus Bell",      event: "Forward" },
      { name: "Cameron Hayes",    event: "Guard" },
      { name: "Donovan Lee",      event: "Forward" },
    ],
    donations: [
      { donor_name: "Patricia N.", amount_cents:  30000, athlete_name: "Isaiah Cooper",   message: "Lions Nation!" },
      { donor_name: "George W.",   amount_cents:  15000, athlete_name: "Darius Webb",     message: "" },
      { donor_name: "Karen S.",    amount_cents:  50000, athlete_name: "Trevon Miles",    message: "Keep working hard!" },
      { donor_name: "Frank D.",    amount_cents:  10000, athlete_name: "Kendall Price",   message: "" },
      { donor_name: "Helen B.",    amount_cents:  20000, athlete_name: "Antoine Jackson", message: "" },
      { donor_name: "Thomas R.",   amount_cents:  75000, athlete_name: "Isaiah Cooper",   message: "Championship bound!" },
      { donor_name: "Nancy C.",    amount_cents:  12500, athlete_name: "Elijah Ross",     message: "" },
    ],
    sponsors: [
      { name: "Westwood Family Dental",   url: "https://example.com", tier: "gold"   },
      { name: "Metro Fitness Center",     url: "https://example.com", tier: "silver" },
      { name: "Academy Pizza & Subs",     url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "🏀", title: "Practice Equipment",    description: "New basketballs, training aids, and ball racks",   sort_order: 0 },
      { icon: "✈️", title: "Tournament Entry Fees",  description: "Regional and state tournament registration",       sort_order: 1 },
      { icon: "👕", title: "Warm-Up Gear",           description: "Team warm-up suits and shooting shirts",           sort_order: 2 },
      { icon: "📊", title: "Stats & Scouting Tools", description: "Game analysis software for the coaching staff",    sort_order: 3 },
      { icon: "🍱", title: "Game Day Meals",         description: "Pre-game meal program for away games",             sort_order: 4 },
    ],
  },
  {
    id:              "baseball",
    sport:           "Baseball",
    icon:            "⚾",
    school_name:     "Lincoln High School",
    mascot:          "Bulldogs",
    season:          "Spring 2026",
    location:        "Lincoln, NE",
    primary_color:   "#b91c1c",
    secondary_color: "#6b7280",
    goal_cents:       700000,
    default_slug:    "demo-lincoln-baseball",
    description:     "Varsity baseball program — 10 players, local business sponsors, and parent booster donations.",
    coach_name:      "Coach Brian Sullivan",
    layout_variant:  "classic",
    athletes: [
      { name: "Ryan Kowalski",    event: "Pitcher" },
      { name: "Cole Harrison",    event: "Catcher" },
      { name: "Tyler Nguyen",     event: "First Base" },
      { name: "Brady Jensen",     event: "Second Base" },
      { name: "Carter Olsen",     event: "Shortstop" },
      { name: "Jake Morrison",    event: "Third Base" },
      { name: "Ethan Caldwell",   event: "Left Field" },
      { name: "Mason Griffith",   event: "Center Field" },
      { name: "Logan Perkins",    event: "Right Field" },
      { name: "Hunter Steele",    event: "Pitcher" },
    ],
    donations: [
      { donor_name: "Carol H.",    amount_cents: 20000, athlete_name: "Ryan Kowalski",  message: "Strike 'em out!" },
      { donor_name: "Steven J.",   amount_cents: 10000, athlete_name: "Cole Harrison",  message: "" },
      { donor_name: "Barbara T.",  amount_cents: 50000, athlete_name: "Tyler Nguyen",   message: "Go Bulldogs!" },
      { donor_name: "William K.",  amount_cents:  5000, athlete_name: "Brady Jensen",   message: "" },
      { donor_name: "Dorothy M.",  amount_cents: 15000, athlete_name: "Carter Olsen",   message: "" },
      { donor_name: "Charles P.",  amount_cents: 25000, athlete_name: "Jake Morrison",  message: "Best third baseman!" },
      { donor_name: "Sandra L.",   amount_cents:  7500, athlete_name: "Ethan Caldwell", message: "" },
    ],
    sponsors: [
      { name: "Lincoln Lumber & Supply",  url: "https://example.com", tier: "gold"   },
      { name: "Cornhusker Auto Repair",   url: "https://example.com", tier: "silver" },
      { name: "Bulldog Burger Stand",     url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "⚾", title: "Pitching Machine",       description: "New pitching machine for batting practice",          sort_order: 0 },
      { icon: "✈️", title: "Travel to Away Games",   description: "Transportation to regional away games",              sort_order: 1 },
      { icon: "👕", title: "Uniforms & Helmets",     description: "Updated game uniforms and batting helmets",          sort_order: 2 },
      { icon: "🏟️", title: "Field Maintenance",      description: "Infield dragging equipment and base set replacement", sort_order: 3 },
      { icon: "🎽", title: "Training Gear",          description: "Batting gloves, wrist guards, and protective gear",  sort_order: 4 },
    ],
  },
  {
    id:              "softball",
    sport:           "Softball",
    icon:            "🥎",
    school_name:     "Meadow Hills High School",
    mascot:          "Panthers",
    season:          "Spring 2026",
    location:        "Meadow Hills, TX",
    primary_color:   "#7e22ce",
    secondary_color: "#f59e0b",
    goal_cents:       600000,
    default_slug:    "demo-meadowhills-softball",
    description:     "Girls varsity softball — 10 athletes, title sponsors, and strong community support.",
    coach_name:      "Coach Maria Castillo",
    layout_variant:  "classic",
    athletes: [
      { name: "Brianna Ortiz",    event: "Pitcher" },
      { name: "Alexis Turner",    event: "Catcher" },
      { name: "Hailey Nguyen",    event: "First Base" },
      { name: "Kayla Johnson",    event: "Second Base" },
      { name: "Sydney Martinez",  event: "Shortstop" },
      { name: "Madison Clark",    event: "Third Base" },
      { name: "Olivia Bennett",   event: "Left Field" },
      { name: "Emma Torres",      event: "Center Field" },
      { name: "Chloe Williams",   event: "Right Field" },
      { name: "Natalie Rivera",   event: "Utility" },
    ],
    donations: [
      { donor_name: "Maria G.",   amount_cents: 25000, athlete_name: "Brianna Ortiz",   message: "Panthera Pride!" },
      { donor_name: "Jose R.",    amount_cents:  7500, athlete_name: "Alexis Turner",   message: "" },
      { donor_name: "Susan F.",   amount_cents: 50000, athlete_name: "Hailey Nguyen",   message: "Love this program!" },
      { donor_name: "Carlos M.",  amount_cents: 10000, athlete_name: "Kayla Johnson",   message: "" },
      { donor_name: "Linda V.",   amount_cents: 15000, athlete_name: "Sydney Martinez", message: "" },
      { donor_name: "Daniel T.",  amount_cents: 20000, athlete_name: "Brianna Ortiz",   message: "Ace pitcher!" },
      { donor_name: "Angela S.",  amount_cents:  5000, athlete_name: "Madison Clark",   message: "" },
    ],
    sponsors: [
      { name: "Meadow Hills Orthodontics",  url: "https://example.com", tier: "gold"   },
      { name: "Prairie Wind Realty",        url: "https://example.com", tier: "silver" },
      { name: "Panther Sports Grill",       url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "🥎", title: "New Softballs & Equipment", description: "Regulation softballs and batting tees",           sort_order: 0 },
      { icon: "👕", title: "Team Uniforms",              description: "Home and away jerseys for the full roster",        sort_order: 1 },
      { icon: "✈️", title: "Tournament Travel",          description: "Entry fees and travel to regional tournaments",   sort_order: 2 },
      { icon: "🏟️", title: "Dugout Improvements",        description: "Dugout seating and weather protection",           sort_order: 3 },
      { icon: "📋", title: "Coaching Clinic",            description: "Advanced coaching certification and clinics",     sort_order: 4 },
    ],
  },
  {
    id:              "volleyball",
    sport:           "Volleyball",
    icon:            "🏐",
    school_name:     "Northside High School",
    mascot:          "Hawks",
    season:          "Fall 2026",
    location:        "Northside, OH",
    primary_color:   "#881337",
    secondary_color: "#94a3b8",
    goal_cents:       500000,
    default_slug:    "demo-northside-volleyball",
    description:     "Girls varsity volleyball — 9 athletes, club-style sponsorships, and tournament fundraising.",
    coach_name:      "Coach Jennifer Park",
    layout_variant:  "classic",
    athletes: [
      { name: "Alyssa Chen",      event: "Outside Hitter" },
      { name: "Taylor Brown",     event: "Middle Blocker" },
      { name: "Megan Wilson",     event: "Setter" },
      { name: "Rachel Kim",       event: "Libero" },
      { name: "Lauren Davis",     event: "Opposite Hitter" },
      { name: "Samantha White",   event: "Middle Blocker" },
      { name: "Ashley Moore",     event: "Outside Hitter" },
      { name: "Jessica Taylor",   event: "Setter" },
      { name: "Brittany Hall",    event: "Defensive Specialist" },
    ],
    donations: [
      { donor_name: "Kevin Y.",   amount_cents: 15000, athlete_name: "Alyssa Chen",     message: "Serve it up!" },
      { donor_name: "Diane B.",   amount_cents:  7500, athlete_name: "Taylor Brown",    message: "" },
      { donor_name: "Andrew P.",  amount_cents: 30000, athlete_name: "Megan Wilson",    message: "Great setter!" },
      { donor_name: "Christine N.", amount_cents: 5000, athlete_name: "Rachel Kim",     message: "" },
      { donor_name: "Mark L.",    amount_cents: 10000, athlete_name: "Lauren Davis",    message: "" },
      { donor_name: "Patricia Z.", amount_cents: 20000, athlete_name: "Alyssa Chen",   message: "Go Hawks!" },
    ],
    sponsors: [
      { name: "Northside Health Clinic",    url: "https://example.com", tier: "gold"   },
      { name: "Hawk's Nest Sports Bar",     url: "https://example.com", tier: "silver" },
      { name: "Great Lakes Chiropractic",   url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "🏐", title: "Competition Volleyballs",  description: "NFHS-approved game balls for home matches",     sort_order: 0 },
      { icon: "✈️", title: "Tournament Registration",  description: "Entry fees for invitational tournaments",        sort_order: 1 },
      { icon: "👕", title: "Uniform Set",              description: "Home and away jersey sets for all players",      sort_order: 2 },
      { icon: "📺", title: "Video Replay System",      description: "Tablet-based video review for match preparation", sort_order: 3 },
      { icon: "💪", title: "Strength Training",        description: "Resistance bands, jump trainers, and agility ladders", sort_order: 4 },
    ],
  },
  {
    id:              "track",
    sport:           "Track & Field",
    icon:            "🏃",
    school_name:     "Summit High School",
    mascot:          "Wildcats",
    season:          "Spring 2026",
    location:        "Summit, CO",
    primary_color:   "#15803d",
    secondary_color: "#eab308",
    goal_cents:       600000,
    default_slug:    "demo-summit-track",
    description:     "Track & Field program — 10 athletes across sprints, distance, and field events with invitational funding.",
    coach_name:      "Coach Marcus Webb",
    layout_variant:  "classic",
    athletes: [
      { name: "DeShawn Morris",   event: "100m / 200m Sprints" },
      { name: "Kyle Erikson",     event: "400m / 800m" },
      { name: "Luis Herrera",     event: "1600m / 3200m Distance" },
      { name: "Aaron Fields",     event: "110m Hurdles" },
      { name: "Jared Kim",        event: "Long Jump / Triple Jump" },
      { name: "Brett Lawson",     event: "High Jump" },
      { name: "Nate Simmons",     event: "Shot Put / Discus" },
      { name: "Owen Cruz",        event: "Pole Vault" },
      { name: "Zach Patterson",   event: "4x100m Relay" },
      { name: "Marcus Allen",     event: "4x400m Relay" },
    ],
    donations: [
      { donor_name: "Gail F.",    amount_cents: 10000, athlete_name: "DeShawn Morris",  message: "Fastest in the state!" },
      { donor_name: "Howard C.",  amount_cents:  5000, athlete_name: "Kyle Erikson",    message: "" },
      { donor_name: "Evelyn M.",  amount_cents: 25000, athlete_name: "Luis Herrera",    message: "Distance runner pride!" },
      { donor_name: "Raymond S.", amount_cents:  7500, athlete_name: "Aaron Fields",    message: "" },
      { donor_name: "Irene B.",   amount_cents: 15000, athlete_name: "Jared Kim",       message: "Go Wildcats!" },
      { donor_name: "Victor L.",  amount_cents: 20000, athlete_name: "DeShawn Morris",  message: "Sprint to glory!" },
      { donor_name: "Gloria A.",  amount_cents:  5000, athlete_name: "Owen Cruz",       message: "" },
    ],
    sponsors: [
      { name: "Summit Running Co.",          url: "https://example.com", tier: "gold"   },
      { name: "Colorado Sports Medicine",    url: "https://example.com", tier: "silver" },
      { name: "High Altitude Nutrition Bar", url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "🏃", title: "Meet Entry Fees",       description: "Registration for invitationals and league meets",     sort_order: 0 },
      { icon: "✈️", title: "State Championship Travel", description: "Travel and lodging for state championships",       sort_order: 1 },
      { icon: "👟", title: "Competition Spikes",    description: "Racing spikes for all event athletes",                sort_order: 2 },
      { icon: "🏟️", title: "Track Resurfacing Fund", description: "Contribution to home track resurfacing project",    sort_order: 3 },
      { icon: "📋", title: "Strength & Conditioning", description: "Off-season training program and coaching",          sort_order: 4 },
    ],
  },
  {
    id:              "soccer",
    sport:           "Soccer",
    icon:            "⚽",
    school_name:     "Lakewood High School",
    mascot:          "Falcons",
    season:          "Fall 2026",
    location:        "Lakewood, WA",
    primary_color:   "#1d4ed8",
    secondary_color: "#f97316",
    goal_cents:       750000,
    default_slug:    "demo-lakewood-soccer",
    description:     "Boys varsity soccer — 11 athletes, regional tournament sponsor packages, active parent community.",
    coach_name:      "Coach Roberto Mendez",
    layout_variant:  "classic",
    athletes: [
      { name: "Cristian Vega",    event: "Goalkeeper" },
      { name: "Pablo Santos",     event: "Right Back" },
      { name: "Marcus Greene",    event: "Center Back" },
      { name: "Andre Dupont",     event: "Left Back" },
      { name: "Kevin Okafor",     event: "Defensive Mid" },
      { name: "Theo Fischer",     event: "Central Midfielder" },
      { name: "Diego Reyes",      event: "Attacking Mid" },
      { name: "Mateo Alvarez",    event: "Right Wing" },
      { name: "Jordan Baptiste",  event: "Left Wing" },
      { name: "Luca Romano",      event: "Striker" },
      { name: "Sandro Petrov",    event: "Forward" },
    ],
    donations: [
      { donor_name: "Isabella Q.", amount_cents: 20000, athlete_name: "Luca Romano",    message: "Hat trick incoming!" },
      { donor_name: "Felix H.",    amount_cents:  7500, athlete_name: "Cristian Vega",  message: "Best keeper around!" },
      { donor_name: "Natalia S.",  amount_cents: 50000, athlete_name: "Mateo Alvarez",  message: "Falcon Up!" },
      { donor_name: "Oscar P.",    amount_cents: 10000, athlete_name: "Diego Reyes",    message: "" },
      { donor_name: "Clara M.",    amount_cents: 15000, athlete_name: "Luca Romano",    message: "" },
      { donor_name: "Bruno T.",    amount_cents: 30000, athlete_name: "Kevin Okafor",   message: "Proud of the team!" },
      { donor_name: "Elena R.",    amount_cents:  5000, athlete_name: "Theo Fischer",   message: "" },
    ],
    sponsors: [
      { name: "Pacific Northwest FC Academy",  url: "https://example.com", tier: "gold"   },
      { name: "Lakewood Sports Therapy",       url: "https://example.com", tier: "silver" },
      { name: "Falcon Wing Sports Bar",        url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "⚽", title: "Match Balls & Gear",    description: "FIFA-quality training and match soccer balls",         sort_order: 0 },
      { icon: "✈️", title: "Tournament Travel",     description: "State and regional tournament entry and travel",       sort_order: 1 },
      { icon: "👕", title: "Kit & Equipment",       description: "Full home and away kits including goalkeeper gear",    sort_order: 2 },
      { icon: "🏟️", title: "Field Lighting",        description: "Portable lighting for evening practice sessions",     sort_order: 3 },
      { icon: "📋", title: "Skills Camp",           description: "Summer elite skills camp with professional coaches",  sort_order: 4 },
    ],
  },
  {
    id:              "xc",
    sport:           "Cross Country",
    icon:            "🏅",
    school_name:     "Valley Ridge High School",
    mascot:          "Mustangs",
    season:          "Fall 2026",
    location:        "Valley Ridge, OR",
    primary_color:   "#78350f",
    secondary_color: "#d97706",
    goal_cents:       400000,
    default_slug:    "demo-valley-xc",
    description:     "Cross country program — 9 runners, course fund, regional meet travel, and strong alumni support.",
    coach_name:      "Coach Stephanie Long",
    layout_variant:  "classic",
    athletes: [
      { name: "Finn Jacobsen",    event: "Varsity Runner" },
      { name: "Elias Thornton",   event: "Varsity Runner" },
      { name: "Samuel Ortega",    event: "Varsity Runner" },
      { name: "Connor Walsh",     event: "Varsity Runner" },
      { name: "Tobias Reed",      event: "Varsity Runner" },
      { name: "Nathan Burke",     event: "JV Runner" },
      { name: "Archer Singh",     event: "JV Runner" },
      { name: "Leo Huang",        event: "JV Runner" },
      { name: "Oliver Park",      event: "JV Runner" },
    ],
    donations: [
      { donor_name: "Alice T.",   amount_cents: 10000, athlete_name: "Finn Jacobsen",   message: "Run like the wind!" },
      { donor_name: "Ralph O.",   amount_cents:  5000, athlete_name: "Elias Thornton",  message: "" },
      { donor_name: "Peggy N.",   amount_cents: 25000, athlete_name: "Samuel Ortega",   message: "State bound!" },
      { donor_name: "Gerald F.",  amount_cents:  7500, athlete_name: "Connor Walsh",    message: "" },
      { donor_name: "Norma S.",   amount_cents: 10000, athlete_name: "Finn Jacobsen",   message: "Go Mustangs!" },
      { donor_name: "Clarence B.", amount_cents: 15000, athlete_name: "Tobias Reed",   message: "Proud alum supporter" },
    ],
    sponsors: [
      { name: "Valley Ridge Running Club",  url: "https://example.com", tier: "gold"   },
      { name: "Mustang Physical Therapy",   url: "https://example.com", tier: "silver" },
      { name: "Trail Mix Cafe",             url: "https://example.com", tier: "bronze" },
    ],
    fund_uses: [
      { icon: "🏅", title: "Invitational Entry Fees",   description: "Registration for regional invitationals and qualifiers", sort_order: 0 },
      { icon: "✈️", title: "State Meet Travel",          description: "Bus transportation and lodging for state championships",  sort_order: 1 },
      { icon: "👟", title: "Racing Shoes & Spikes",      description: "Cross country racing flats and spike plates for all runners", sort_order: 2 },
      { icon: "🌿", title: "Course Maintenance",         description: "Home course marking, mowing, and signage",               sort_order: 3 },
      { icon: "📋", title: "Summer Training Program",    description: "Structured summer mileage program with coaching support", sort_order: 4 },
    ],
  },
];
